"""
NexClaim Pre-Assessment Brief Generator.

Compiles a structured, reviewer-ready summary from all AI pipeline outputs.
"""

import json
import logging
from datetime import datetime
from typing import Optional

logger = logging.getLogger(__name__)


class PreAssessmentBriefGenerator:
    """Generates a comprehensive pre-assessment brief for reviewer consumption."""

    def generate(
        self,
        claim_id: int,
        policyholder_name: str,
        policy_number: str,
        extracted_fields: dict,
        validation: dict,
        risk_result: dict,
        confidence_score: float,
        recommendation: dict,
        explanation: str,
    ) -> str:
        """
        Generate a complete pre-assessment brief document.

        Returns:
            Formatted markdown string ready for reviewer display.
        """
        generated_at = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")

        action = recommendation.get("action", "UNKNOWN")
        action_labels = {
            "APPROVE_RECOMMENDATION": "✅ APPROVE RECOMMENDED",
            "REJECT_RECOMMENDATION": "❌ REJECT RECOMMENDED",
            "ESCALATE": "⚠️ ESCALATE TO ADMIN",
        }
        action_label = action_labels.get(action, action)

        risk_level = risk_result.get("risk_level", "UNKNOWN")
        risk_probability = risk_result.get("probability", 0.0)
        confidence_pct = f"{confidence_score * 100:.1f}%"

        brief = f"""# NexClaim Pre-Assessment Brief
**Claim ID:** #{claim_id}
**Generated:** {generated_at}
**Policyholder:** {policyholder_name}
**Policy Number:** {policy_number or 'Not Extracted'}

---

## 🎯 AI Recommendation
**{action_label}**
**Confidence Score:** {confidence_pct}
**Risk Level:** {risk_level} ({risk_probability:.1%} probability)

---

## 📋 Extracted Claim Information
| Field | Value |
|-------|-------|
| Patient Name | {extracted_fields.get('patient_name') or 'Not Found'} |
| Hospital | {extracted_fields.get('hospital_name') or 'Not Found'} |
| Diagnosis | {extracted_fields.get('diagnosis') or 'Not Found'} |
| Admission Date | {extracted_fields.get('admission_date_raw') or 'Not Found'} |
| Discharge Date | {extracted_fields.get('discharge_date_raw') or 'Not Found'} |
| Claim Amount | ₹{extracted_fields.get('claim_amount', 0):,.2f} |

---

## ✅ Policy Validation Results
| Check | Result |
|-------|--------|
| Policy Active | {'✅ Pass' if validation.get('is_policy_active') else '❌ Fail'} |
| Premium Paid | {'✅ Pass' if validation.get('is_premium_paid') else '❌ Fail'} |
| Disease Covered | {'✅ Pass' if validation.get('is_disease_covered') else '❌ Fail'} |
| Within Limit | {'✅ Pass' if validation.get('is_within_limit') else '❌ Fail'} |
| Waiting Period Met | {'✅ Pass' if validation.get('is_waiting_period_met') else '❌ Fail'} |

---

## ⚡ Decision Factors
"""
        for reason in recommendation.get("reasons", []):
            brief += f"- {reason}\n"

        brief += f"""
---

## 🔍 Detailed AI Explanation
{explanation}

---
*This brief was auto-generated by the NexClaim AI Engine.*
*Reviewer must verify all uploaded documents independently.*
*Claim ID #{claim_id} | {generated_at}*
"""
        logger.info("Pre-assessment brief generated for claim #%d", claim_id)
        return brief


brief_generator = PreAssessmentBriefGenerator()
