"""
NexClaim Explainability Module.

Generates human-readable, reviewer-friendly explanations
for AI recommendation decisions.
"""

import logging

logger = logging.getLogger(__name__)


class ExplainabilityGenerator:
    """Generates natural language explanations for claim AI decisions."""

    def generate(
        self,
        validation: dict,
        risk_level: str,
        risk_probability: float,
        confidence_score: float,
        recommendation_action: str,
        reasons: list[str],
    ) -> str:
        """
        Generate a detailed, human-readable explanation.

        Returns:
            Formatted explanation string for reviewer consumption.
        """
        lines = []
        lines.append("## AI Assessment Explanation\n")

        # Recommendation summary
        action_map = {
            "APPROVE_RECOMMENDATION": "✅ APPROVE",
            "REJECT_RECOMMENDATION": "❌ REJECT",
            "ESCALATE": "⚠️ ESCALATE TO ADMIN",
        }
        action_label = action_map.get(recommendation_action, recommendation_action)
        lines.append(f"**Recommendation:** {action_label}\n")
        lines.append(f"**Risk Level:** {risk_level} ({risk_probability:.1%} probability)")
        lines.append(f"**Confidence Score:** {confidence_score:.1%}\n")

        # Policy validation breakdown
        lines.append("### Policy Validation Results")
        validation_checks = [
            ("is_policy_active", "Policy Active Status"),
            ("is_premium_paid", "Premium Payment Status"),
            ("is_disease_covered", "Disease Coverage"),
            ("is_within_limit", "Coverage Limit Compliance"),
            ("is_waiting_period_met", "Waiting Period Compliance"),
        ]
        for key, label in validation_checks:
            status = validation.get(key, False)
            icon = "✅" if status else "❌"
            lines.append(f"- {icon} {label}: {'Passed' if status else 'Failed'}")

        # Reasons
        lines.append("\n### Decision Factors")
        for reason in reasons:
            lines.append(f"- {reason}")

        # Additional context
        lines.append("\n### Risk Assessment Details")
        report = validation.get("report", {})
        for check_name, check_data in report.items():
            if isinstance(check_data, dict):
                msg = check_data.get("message", "")
                lines.append(f"- {msg}")

        lines.append("\n---")
        lines.append("*This assessment was generated by the NexClaim AI Engine.*")
        lines.append("*Reviewer should verify all documents before making a final decision.*")

        explanation = "\n".join(lines)
        logger.info("Explainability report generated (%d chars)", len(explanation))
        return explanation


explainability_generator = ExplainabilityGenerator()
